# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AuthorisationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthorisationWindow(object):
    def setupUi(self, AuthorisationWindow):
        AuthorisationWindow.setObjectName("AuthorisationWindow")
        AuthorisationWindow.resize(500, 425)
        AuthorisationWindow.setMinimumSize(QtCore.QSize(500, 425))
        AuthorisationWindow.setMaximumSize(QtCore.QSize(500, 425))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(233, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 133, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        AuthorisationWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        AuthorisationWindow.setFont(font)
        AuthorisationWindow.setStyleSheet("background: rgb(233, 234, 255)")
        self.loginLabel = QtWidgets.QLabel(AuthorisationWindow)
        self.loginLabel.setGeometry(QtCore.QRect(200, 40, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("")
        self.loginLabel.setTextFormat(QtCore.Qt.AutoText)
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.loginLineEdit = QtWidgets.QLineEdit(AuthorisationWindow)
        self.loginLineEdit.setGeometry(QtCore.QRect(125, 80, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.loginLineEdit.setFont(font)
        self.loginLineEdit.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid blue;\n"
"}\n"
"")
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.passwordLabel = QtWidgets.QLabel(AuthorisationWindow)
        self.passwordLabel.setGeometry(QtCore.QRect(200, 130, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("")
        self.passwordLabel.setTextFormat(QtCore.Qt.AutoText)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLineEdit = QtWidgets.QLineEdit(AuthorisationWindow)
        self.passwordLineEdit.setGeometry(QtCore.QRect(125, 170, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid blue;\n"
"}")
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.authorisationButton = QtWidgets.QPushButton(AuthorisationWindow)
        self.authorisationButton.setGeometry(QtCore.QRect(162, 220, 176, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.authorisationButton.setFont(font)
        self.authorisationButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid blue;\n"
"}\n"
"\n"
"")
        self.authorisationButton.setObjectName("authorisationButton")
        self.registrationButton = QtWidgets.QPushButton(AuthorisationWindow)
        self.registrationButton.setGeometry(QtCore.QRect(162, 265, 176, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.registrationButton.setFont(font)
        self.registrationButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid blue;\n"
"}\n"
"")
        self.registrationButton.setObjectName("registrationButton")
        self.forgotPasswordButton = QtWidgets.QPushButton(AuthorisationWindow)
        self.forgotPasswordButton.setGeometry(QtCore.QRect(162, 310, 176, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        self.forgotPasswordButton.setFont(font)
        self.forgotPasswordButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: blue;\n"
"    text-decoration: underline; \n"
"}\n"
"QPushButton:hover {\n"
"    color: red; \n"
"}\n"
"")
        self.forgotPasswordButton.setObjectName("forgotPasswordButton")
        self.regInfoLabel = QtWidgets.QLabel(AuthorisationWindow)
        self.regInfoLabel.setGeometry(QtCore.QRect(75, 355, 350, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.regInfoLabel.setFont(font)
        self.regInfoLabel.setStyleSheet("color: red;")
        self.regInfoLabel.setText("")
        self.regInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.regInfoLabel.setObjectName("regInfoLabel")
        self.passwordCheckBox = QtWidgets.QCheckBox(AuthorisationWindow)
        self.passwordCheckBox.setGeometry(QtCore.QRect(390, 170, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.passwordCheckBox.setFont(font)
        self.passwordCheckBox.setText("")
        self.passwordCheckBox.setObjectName("passwordCheckBox")

        self.retranslateUi(AuthorisationWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthorisationWindow)

    def retranslateUi(self, AuthorisationWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthorisationWindow.setWindowTitle(_translate("AuthorisationWindow", "AuthorisationWindow"))
        self.loginLabel.setText(_translate("AuthorisationWindow", "Логин"))
        self.loginLineEdit.setPlaceholderText(_translate("AuthorisationWindow", "Введите логин"))
        self.passwordLabel.setText(_translate("AuthorisationWindow", "Пароль"))
        self.passwordLineEdit.setPlaceholderText(_translate("AuthorisationWindow", "Введите пароль"))
        self.authorisationButton.setText(_translate("AuthorisationWindow", "Войти"))
        self.registrationButton.setText(_translate("AuthorisationWindow", "Зарегистрироваться"))
        self.forgotPasswordButton.setText(_translate("AuthorisationWindow", "Забыли пароль?"))
