# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(620, 240)
        EditWindow.setMinimumSize(QtCore.QSize(620, 240))
        EditWindow.setMaximumSize(QtCore.QSize(620, 240))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        EditWindow.setFont(font)
        EditWindow.setStyleSheet("background: rgb(233, 234, 255)")
        self.editButtonBox = QtWidgets.QDialogButtonBox(EditWindow)
        self.editButtonBox.setGeometry(QtCore.QRect(60, 180, 340, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        self.editButtonBox.setFont(font)
        self.editButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.editButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.editButtonBox.setObjectName("editButtonBox")
        self.editBeforeInfoLabel = QtWidgets.QLabel(EditWindow)
        self.editBeforeInfoLabel.setGeometry(QtCore.QRect(20, 130, 560, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.editBeforeInfoLabel.setFont(font)
        self.editBeforeInfoLabel.setStyleSheet("color: blue;")
        self.editBeforeInfoLabel.setText("")
        self.editBeforeInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.editBeforeInfoLabel.setObjectName("editBeforeInfoLabel")
        self.editCombobox = QtWidgets.QComboBox(EditWindow)
        self.editCombobox.setGeometry(QtCore.QRect(20, 30, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.editCombobox.setFont(font)
        self.editCombobox.setStyleSheet("QComboBox {\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"}")
        self.editCombobox.setObjectName("editCombobox")
        self.editLineEdit = QtWidgets.QLineEdit(EditWindow)
        self.editLineEdit.setGeometry(QtCore.QRect(190, 30, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.editLineEdit.setFont(font)
        self.editLineEdit.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid blue;\n"
"}")
        self.editLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.editLineEdit.setObjectName("editLineEdit")
        self.editDateEdit = QtWidgets.QDateEdit(EditWindow)
        self.editDateEdit.setGeometry(QtCore.QRect(470, 30, 110, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        self.editDateEdit.setFont(font)
        self.editDateEdit.setStyleSheet("QDateEdit {\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"}")
        self.editDateEdit.setCalendarPopup(True)
        self.editDateEdit.setObjectName("editDateEdit")
        self.beforeLabel = QtWidgets.QLabel(EditWindow)
        self.beforeLabel.setGeometry(QtCore.QRect(260, 80, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.beforeLabel.setFont(font)
        self.beforeLabel.setStyleSheet("")
        self.beforeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.beforeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.beforeLabel.setObjectName("beforeLabel")

        self.retranslateUi(EditWindow)
        self.editButtonBox.accepted.connect(EditWindow.accept) # type: ignore
        self.editButtonBox.rejected.connect(EditWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "EditWindow"))
        self.editLineEdit.setPlaceholderText(_translate("EditWindow", "Введите сумму расхода"))
        self.beforeLabel.setText(_translate("EditWindow", "До"))
