# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ForgotPasswordWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForgotPasswordWindow(object):
    def setupUi(self, ForgotPasswordWindow):
        ForgotPasswordWindow.setObjectName("ForgotPasswordWindow")
        ForgotPasswordWindow.resize(400, 365)
        ForgotPasswordWindow.setMinimumSize(QtCore.QSize(400, 365))
        ForgotPasswordWindow.setMaximumSize(QtCore.QSize(400, 365))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        ForgotPasswordWindow.setFont(font)
        ForgotPasswordWindow.setWindowOpacity(1.0)
        ForgotPasswordWindow.setStyleSheet("background: rgb(233, 234, 255)")
        self.forgotLoginLabel_2 = QtWidgets.QLabel(ForgotPasswordWindow)
        self.forgotLoginLabel_2.setGeometry(QtCore.QRect(150, 30, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.forgotLoginLabel_2.setFont(font)
        self.forgotLoginLabel_2.setStyleSheet("")
        self.forgotLoginLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.forgotLoginLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forgotLoginLabel_2.setObjectName("forgotLoginLabel_2")
        self.forgotLoginLineEdit = QtWidgets.QLineEdit(ForgotPasswordWindow)
        self.forgotLoginLineEdit.setGeometry(QtCore.QRect(75, 70, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.forgotLoginLineEdit.setFont(font)
        self.forgotLoginLineEdit.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid blue;\n"
"}\n"
"")
        self.forgotLoginLineEdit.setObjectName("forgotLoginLineEdit")
        self.forgotPasswordLabel = QtWidgets.QLabel(ForgotPasswordWindow)
        self.forgotPasswordLabel.setGeometry(QtCore.QRect(150, 120, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.forgotPasswordLabel.setFont(font)
        self.forgotPasswordLabel.setStyleSheet("")
        self.forgotPasswordLabel.setTextFormat(QtCore.Qt.AutoText)
        self.forgotPasswordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.forgotPasswordLabel.setObjectName("forgotPasswordLabel")
        self.forgotPasswordLineEdit = QtWidgets.QLineEdit(ForgotPasswordWindow)
        self.forgotPasswordLineEdit.setGeometry(QtCore.QRect(75, 160, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.forgotPasswordLineEdit.setFont(font)
        self.forgotPasswordLineEdit.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid blue;\n"
"}")
        self.forgotPasswordLineEdit.setObjectName("forgotPasswordLineEdit")
        self.forgotPasswordLineEdit2 = QtWidgets.QLineEdit(ForgotPasswordWindow)
        self.forgotPasswordLineEdit2.setGeometry(QtCore.QRect(75, 210, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.forgotPasswordLineEdit2.setFont(font)
        self.forgotPasswordLineEdit2.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid blue;\n"
"}")
        self.forgotPasswordLineEdit2.setObjectName("forgotPasswordLineEdit2")
        self.forgotPasswordButton = QtWidgets.QPushButton(ForgotPasswordWindow)
        self.forgotPasswordButton.setGeometry(QtCore.QRect(120, 260, 176, 25))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.forgotPasswordButton.setFont(font)
        self.forgotPasswordButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid blue;\n"
"}\n"
"")
        self.forgotPasswordButton.setObjectName("forgotPasswordButton")
        self.forgotRegInfoLabel = QtWidgets.QLabel(ForgotPasswordWindow)
        self.forgotRegInfoLabel.setGeometry(QtCore.QRect(25, 305, 350, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.forgotRegInfoLabel.setFont(font)
        self.forgotRegInfoLabel.setStyleSheet("color: red;")
        self.forgotRegInfoLabel.setText("")
        self.forgotRegInfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.forgotRegInfoLabel.setObjectName("forgotRegInfoLabel")
        self.forgotPasswordCheckBox = QtWidgets.QCheckBox(ForgotPasswordWindow)
        self.forgotPasswordCheckBox.setGeometry(QtCore.QRect(340, 160, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.forgotPasswordCheckBox.setFont(font)
        self.forgotPasswordCheckBox.setText("")
        self.forgotPasswordCheckBox.setObjectName("forgotPasswordCheckBox")
        self.forgotPasswordCheckBox2 = QtWidgets.QCheckBox(ForgotPasswordWindow)
        self.forgotPasswordCheckBox2.setGeometry(QtCore.QRect(340, 210, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.forgotPasswordCheckBox2.setFont(font)
        self.forgotPasswordCheckBox2.setText("")
        self.forgotPasswordCheckBox2.setObjectName("forgotPasswordCheckBox2")

        self.retranslateUi(ForgotPasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ForgotPasswordWindow)

    def retranslateUi(self, ForgotPasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ForgotPasswordWindow.setWindowTitle(_translate("ForgotPasswordWindow", "ForgotPasswordWindow"))
        self.forgotLoginLabel_2.setText(_translate("ForgotPasswordWindow", "Логин"))
        self.forgotLoginLineEdit.setPlaceholderText(_translate("ForgotPasswordWindow", "Введите логин"))
        self.forgotPasswordLabel.setText(_translate("ForgotPasswordWindow", "Пароль"))
        self.forgotPasswordLineEdit.setPlaceholderText(_translate("ForgotPasswordWindow", "Введите новый пароль"))
        self.forgotPasswordLineEdit2.setPlaceholderText(_translate("ForgotPasswordWindow", "Повторите пароль"))
        self.forgotPasswordButton.setText(_translate("ForgotPasswordWindow", "Сохранить"))
