# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'incomesChart.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_incomesChart(object):
    def setupUi(self, incomesChart):
        incomesChart.setObjectName("incomesChart")
        incomesChart.resize(1300, 900)
        incomesChart.setMinimumSize(QtCore.QSize(1300, 900))
        incomesChart.setMaximumSize(QtCore.QSize(1300, 900))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        incomesChart.setFont(font)
        incomesChart.setStyleSheet("background: rgb(233, 234, 255)")
        self.incomesGraphicsView = QChartView(incomesChart)
        self.incomesGraphicsView.setGeometry(QtCore.QRect(50, 100, 1200, 750))
        self.incomesGraphicsView.setObjectName("incomesGraphicsView")
        self.chartIncomesLabel = QtWidgets.QLabel(incomesChart)
        self.chartIncomesLabel.setGeometry(QtCore.QRect(280, 35, 180, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.chartIncomesLabel.setFont(font)
        self.chartIncomesLabel.setStyleSheet("")
        self.chartIncomesLabel.setTextFormat(QtCore.Qt.AutoText)
        self.chartIncomesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.chartIncomesLabel.setObjectName("chartIncomesLabel")
        self.chartFirstDateEdit = QtWidgets.QDateEdit(incomesChart)
        self.chartFirstDateEdit.setGeometry(QtCore.QRect(480, 35, 110, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        self.chartFirstDateEdit.setFont(font)
        self.chartFirstDateEdit.setStyleSheet("QDateEdit {\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"}")
        self.chartFirstDateEdit.setCalendarPopup(True)
        self.chartFirstDateEdit.setObjectName("chartFirstDateEdit")
        self.chartIncomesLabel2 = QtWidgets.QLabel(incomesChart)
        self.chartIncomesLabel2.setGeometry(QtCore.QRect(610, 35, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        self.chartIncomesLabel2.setFont(font)
        self.chartIncomesLabel2.setStyleSheet("")
        self.chartIncomesLabel2.setTextFormat(QtCore.Qt.AutoText)
        self.chartIncomesLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.chartIncomesLabel2.setObjectName("chartIncomesLabel2")
        self.chartSecondDateEdit = QtWidgets.QDateEdit(incomesChart)
        self.chartSecondDateEdit.setGeometry(QtCore.QRect(730, 35, 110, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        self.chartSecondDateEdit.setFont(font)
        self.chartSecondDateEdit.setStyleSheet("QDateEdit {\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"}")
        self.chartSecondDateEdit.setCalendarPopup(True)
        self.chartSecondDateEdit.setObjectName("chartSecondDateEdit")

        self.retranslateUi(incomesChart)
        QtCore.QMetaObject.connectSlotsByName(incomesChart)

    def retranslateUi(self, incomesChart):
        _translate = QtCore.QCoreApplication.translate
        incomesChart.setWindowTitle(_translate("incomesChart", "incomesChart"))
        self.chartIncomesLabel.setText(_translate("incomesChart", "Показать доходы с"))
        self.chartIncomesLabel2.setText(_translate("incomesChart", "по"))
from PyQt5.QtChart import QChartView
